### ISSUE TITLE
 500 Server Error: Internal Server Error for url

### ISSUE THREAD

**Issue by fyksen** [mathiazom/pasjonsfrukt#14]
* Dette er med `:schibsted-auth` containeren. (og schibsted brukernavn og passord).
* Sluttet å fungere en gang etter 2. Oktober.

```
root@8f83652e5107:/app# pasjonsfrukt harvest
Traceback (most recent call last):

  File "/usr/local/bin/pasjonsfrukt", line 6, in <module>
    sys.exit(cli())

  File "/app/pasjonsfrukt/cli.py", line 33, in harvest
    client = get_podme_client(config.auth.email, config.auth.password)

  File "/app/pasjonsfrukt/main.py", line 20, in get_podme_client
    client.login()

  File "/usr/local/lib/python3.10/site-packages/podme_api/client.py", line 35, in login
    self._get_oauth_token()

  File "/usr/local/lib/python3.10/site-packages/podme_api/client.py", line 277, in _get_oauth_token
    auth_finish_res.raise_for_status()

  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://podme.com/auth/handleSchibstedLogin?code=<redacted>&state=%7B%22returnUrl%22%3A%22https%3A%2F%2Fpodme.com%2Fno%2Foppdag%22%2C%22uuid%22%3A%22cef8d97e-a29a-468a-a867-5911862e7f63%22%7D

```

* Testet fra to forskjellige IPer for å utelukke rate-limits på IP.
* Logget inn på podme.com for å verifisere at brukernavn og passord fungerer som det skal.
* 2FA er ikke aktivert på brukeren.

**Comment by fyksen** [comment]
Ouf. Ser nå det har tikket inn tofaktor eposter til meg fra schibsted. Til tross for disse kontoinstillingene.

![image](https://github.com/user-attachments/assets/3368da78-e2bf-4748-94ef-9e03d06f19a5)

Er det mulig å bruke `:schibsted-auth` med 2fa autentiseringsapp?

**Comment by mathiazom** [comment]
> Ouf. Ser nå det har tikket inn tofaktor eposter til meg fra schibsted. Til tross for disse kontoinstillingene.

Ikke umulig at de begynner å kreve det fremover 🫣

> Er det mulig å bruke :schibsted-auth med 2fa autentiseringsapp?

Per nå er det ingen støtte for det nei, men burde være en [smal sak](https://pypi.org/project/mintotp/) å generere TOTP hvis man oppgir secret sammen med brukernavn/passord. Jeg undersøker nærmere 👀

**Comment by bendikrb** [comment]
FYI; Jeg skal se på dette i [podme_api](https://github.com/bendikrb/podme_api) i kveld.. 😊

**Comment by mathiazom** [comment]
[`schibsted-auth`](https://github.com/mathiazom/pasjonsfrukt/pkgs/container/pasjonsfrukt/286839293?tag=schibsted-auth) burde funke igjen nå 🤞 takket være @bendikrb ❤️ 

Foreløpig ikke tatt høyde for 2FA, så satser på at det ikke kreves med det første...

**Comment by fyksen** [comment]
It works. Takker!

**Comment by mathiazom** [comment]
> It works. Takker!

Så bra 🤗 

Lukker denne nå, så får vi eventuelt lage en ny issue hvis 2FA skaper trøbbel.
