### ISSUE TITLE
Possible to limit number of episodes that is harvested?

### ISSUE THREAD

**Issue by fyksen** [mathiazom/pasjonsfrukt#8]
First off, thanks for creating this! 😍

Is it possible to limit the number of podcasts that is harvested?
Papaya does now have so many episodes that we reach a timeout if you try to harvest everyone at once. 

After 196 episodes I got error:

`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.podme.com', port=443): Max retries exceeded with url: /web/api/v2/episode/1021584 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f881c165f30>: Failed to establish a new connection: [Errno -3] Try again'))
`

**Comment by mathiazom** [comment]
Nice feedback :+1: 

Are you thinking a limit like "only harvest the 50 most recent episodes", or rather "harvest at most 50 episodes at a time"? 

The former actually seems like a nice feature in itself, even if we didn't have the error above. I think a per-podcast optional value would be appropriate.

The latter seems to me like an internal fix for the above error, where the harvesting is performed in "bulk".

I guess we could do both :upside_down_face:

**Comment by fyksen** [comment]
I was thinking the "only harvest the 50 most recent episodes" option. It would be very nice for podcast like Aftenpodden where I really don't care to store all the episodes.

**Comment by mathiazom** [comment]
39a147b7c2fe55ec82a280ee183ff18a2d64a1fe introduces the config option `most_recent_episodes_limit` for each podcast item. This should allow you to say "only harvest the 50 most recent episodes for Papaya" like this:
```
podcasts:
  papaya:
    most_recent_episodes_limit: 50
```
I have only done some initial testing, so feel free to report back if you have any issues
